# Generated by Django 3.1.3 on 2021-01-11 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kondate_app', '0002_auto_20210111_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='menus',
            name='ingredient',
        ),
        migrations.DeleteModel(
            name='amount_of_ingredients',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kondate_app.menus'),
        ),
    ]
